# Generated by Django 5.1.1 on 2025-04-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_Country', models.AutoField(primary_key=True, serialize=False)),
                ('name_Country', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markes',
            fields=[
                ('idMarke', models.AutoField(primary_key=True, serialize=False)),
                ('name_marke', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id_Place', models.AutoField(primary_key=True, serialize=False)),
                ('name_place', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('name_rol', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statu',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name_status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_inventari',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_technologi',
            fields=[
                ('idType_technologi', models.AutoField(primary_key=True, serialize=False)),
                ('name_technologi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id_typeDocument', models.AutoField(primary_key=True, serialize=False)),
                ('name_documento', models.CharField(max_length=100, unique=True)),
                ('simbols', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False)),
                ('name_department', models.CharField(max_length=100, unique=True)),
                ('id_Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_City', models.AutoField(primary_key=True, serialize=False)),
                ('name_City', models.CharField(max_length=100, unique=True)),
                ('id_Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.country')),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.department')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('name_sede', models.CharField(max_length=100, unique=True)),
                ('direccion_sede', models.CharField(max_length=100, unique=True)),
                ('contact_one', models.BigIntegerField(null=True)),
                ('contact_two', models.BigIntegerField(null=True)),
                ('date_register', models.DateTimeField(auto_now=True)),
                ('id_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.city')),
            ],
        ),
        migrations.CreateModel(
            name='centro',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('name_centro', models.CharField(max_length=100, null=True)),
                ('descripcion_centro', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Material_Didactico',
            fields=[
                ('idMaterial_didactico', models.AutoField(primary_key=True, serialize=False)),
                ('name_material', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('series_Manufactures', models.TextField()),
                ('series_sena', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('id_Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.place')),
                ('ID_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.status_inventari')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnology',
            fields=[
                ('idTecnology', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristics', models.TextField()),
                ('series_Manufactures', models.TextField()),
                ('series_sena', models.TextField()),
                ('date_register', models.DateTimeField(auto_now=True)),
                ('ID_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.status_inventari')),
                ('idMarke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.markes')),
                ('id_Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.place')),
                ('idType_technologi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.type_technologi')),
            ],
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('idLend', models.AutoField(primary_key=True, serialize=False)),
                ('date_lend', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField()),
                ('date_return', models.DateTimeField(default=None, null=True)),
                ('idMaterial_didactico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.material_didactico')),
                ('idTecnology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.tecnology')),
            ],
        ),
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('idUbication', models.AutoField(primary_key=True, serialize=False)),
                ('name_Ubication', models.CharField(max_length=100)),
                ('description_ubication', models.TextField()),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.centro')),
            ],
        ),
        migrations.AddField(
            model_name='tecnology',
            name='idUbication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubication'),
        ),
        migrations.AddField(
            model_name='material_didactico',
            name='idUbication',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='inventario.ubication'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('primary_contact', models.BigIntegerField()),
                ('secondary_contact', models.BigIntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.centro')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.rol')),
                ('id_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.statu')),
                ('id_type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.typedocument')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id_password', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.user')),
            ],
        ),
    ]
