# Generated by Django 5.1.1 on 2025-05-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_priority_report_status_report_type_report_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='languaje',
            fields=[
                ('id_languaje', models.AutoField(primary_key=True, serialize=False)),
                ('name_languaje', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id_configuration', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.user')),
                ('id_languaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.languaje')),
            ],
        ),
        migrations.CreateModel(
            name='Coversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('context', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.configuration')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.user')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('question_user', models.TextField()),
                ('answer_ia', models.TextField()),
                ('correct_answer', models.TextField()),
                ('context_question', models.TextField()),
                ('metadatas', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.user')),
            ],
        ),
    ]
