# Generated by Django 5.1.1 on 2025-05-01 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_languaje_configuration_coversation_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelDificultad',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('valor_numerico', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Niveles de Dificultad',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Aprendizaje',
            fields=[
                ('id_aprendizaje', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='Texto de entrada para el modelo')),
                ('respuesta_esperada', models.TextField(help_text='Respuesta ideal para este prompt')),
                ('palabras_clave', models.JSONField(blank=True, help_text='Lista de palabras clave  aprendizaje', null=True)),
                ('contexto', models.TextField(blank=True, help_text='Información de contexto adicional', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='inventario.categoria')),
                ('dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='inventario.niveldificultad')),
                ('tags', models.ManyToManyField(related_name='aprendizajes', to='inventario.tag')),
            ],
            options={
                'verbose_name_plural': 'Aprendizajes',
            },
        ),
        migrations.CreateModel(
            name='EjemploInteraccion',
            fields=[
                ('id_ejemplo', models.AutoField(primary_key=True, serialize=False)),
                ('consulta_usuario', models.TextField(help_text='Ejemplo de consulta del usuario')),
                ('respuesta_modelo', models.TextField(help_text='Respuesta apropiada del modelo')),
                ('contexto_previo', models.TextField(blank=True, help_text='Interacción previa relevante', null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplos', to='inventario.aprendizaje')),
            ],
        ),
    ]
